-- PostgreSQL baseline for the complete JPA model (13 entities).
-- The legacy database dump is intentionally not used as the schema source.

CREATE TABLE nhommau (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten varchar(255) NOT NULL UNIQUE,
    mota text,
    trangthai integer NOT NULL DEFAULT 1 CHECK (trangthai IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE nguoidung (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten varchar(100) NOT NULL,
    tendangnhap varchar(50) NOT NULL UNIQUE,
    matkhau varchar(255) NOT NULL,
    email varchar(100) NOT NULL UNIQUE,
    sodienthoai varchar(20),
    ngaysinh date,
    gioitinh varchar(10),
    diachi varchar(255),
    latitude double precision DEFAULT 21.030653,
    longitude double precision DEFAULT 105.847130,
    nhommauid integer REFERENCES nhommau(id) ON DELETE SET NULL,
    yeutorh varchar(1),
    tiensubenh text,
    cannang numeric(5, 2),
    chieucao numeric(5, 2),
    vaitro varchar(20) NOT NULL,
    trangthai integer NOT NULL DEFAULT 1 CHECK (trangthai IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE thongtinnhanvien (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    masonhanvien varchar(50) NOT NULL UNIQUE,
    chucvu varchar(100),
    phongban varchar(100),
    ngayvaolam date,
    trangthailamviec varchar(255),
    nguoidungid integer NOT NULL UNIQUE REFERENCES nguoidung(id) ON DELETE CASCADE,
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hoatdonghienmau (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten varchar(255) NOT NULL,
    ngaybatdau date NOT NULL,
    ngayketthuc date NOT NULL,
    diadiem varchar(255) NOT NULL,
    mota varchar(255) NOT NULL,
    soluongnguoitoida integer NOT NULL CHECK (soluongnguoitoida > 0),
    soluongnguoidangkyhientai integer NOT NULL DEFAULT 0 CHECK (soluongnguoidangkyhientai >= 0),
    nguoitaoid integer REFERENCES nguoidung(id) ON DELETE SET NULL,
    trangthaihoatdong varchar(20),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_activity_dates CHECK (ngayketthuc >= ngaybatdau),
    CONSTRAINT ck_activity_capacity CHECK (soluongnguoidangkyhientai <= soluongnguoitoida),
    CONSTRAINT ck_activity_status CHECK (trangthaihoatdong IS NULL OR trangthaihoatdong IN ('sapdienra', 'dangdienra', 'daketthuc', 'huy'))
);

CREATE TABLE yeucauhienmau (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoihienid integer NOT NULL REFERENCES nguoidung(id) ON DELETE RESTRICT,
    hoatdonghienmauid integer REFERENCES hoatdonghienmau(id) ON DELETE SET NULL,
    ngayhienmaudukien date NOT NULL,
    ngayphuchoigannhat date,
    ghichu text,
    nguoiduyetid integer REFERENCES nguoidung(id) ON DELETE SET NULL,
    ngayduyet timestamp(6) without time zone,
    soluong integer NOT NULL CHECK (soluong > 0 AND soluong <= 2000),
    loaihien varchar(20) NOT NULL DEFAULT 'toanphan',
    trangthai varchar(20) NOT NULL DEFAULT 'dangcho' CHECK (trangthai IN ('dangcho', 'huy', 'xacnhan', 'tuchoi', 'dahien')),
    suckhoehientai varchar(255) NOT NULL DEFAULT '',
    formkham varchar(255) NOT NULL DEFAULT '',
    dangmangthai integer NOT NULL DEFAULT 0 CHECK (dangmangthai IN (0, 1)),
    macbenhtruyennhiem integer NOT NULL DEFAULT 0 CHECK (macbenhtruyennhiem IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_donation_recovery_date CHECK (ngayphuchoigannhat IS NULL OR ngayphuchoigannhat < ngayhienmaudukien)
);

CREATE TABLE yeucaucanmau (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoinhanid integer REFERENCES nguoidung(id) ON DELETE SET NULL,
    ngaynhanmaudukien date,
    nhommauid integer NOT NULL REFERENCES nhommau(id) ON DELETE RESTRICT,
    thanhphanmaucan varchar(255),
    soluongdonvi integer NOT NULL CHECK (soluongdonvi > 0 AND soluongdonvi <= 100),
    lydo varchar(255),
    khancap boolean NOT NULL DEFAULT false,
    diachinhanmau varchar(255),
    ghichu varchar(255),
    nguoiduyetid integer REFERENCES nguoidung(id) ON DELETE SET NULL,
    ngayduyet timestamp(6) without time zone,
    trangthai varchar(20) NOT NULL DEFAULT 'dangcho' CHECK (trangthai IN ('dangcho', 'huy', 'dacomau', 'dahoanthanh')),
    suckhoehientai varchar(255) NOT NULL DEFAULT '',
    dangmangthai integer NOT NULL DEFAULT 0 CHECK (dangmangthai IN (0, 1)),
    formkham varchar(255) NOT NULL DEFAULT '',
    macbenhtruyennhiem integer NOT NULL DEFAULT 0 CHECK (macbenhtruyennhiem IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0
);

CREATE TABLE khodonvimau (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhommauid integer REFERENCES nhommau(id) ON DELETE SET NULL,
    thanhphan varchar(255) NOT NULL DEFAULT 'toanphan',
    soluong integer NOT NULL CHECK (soluong > 0),
    ngaylaymau timestamp(6) without time zone,
    ngayhethan timestamp(6) without time zone,
    nguoihienid integer REFERENCES nguoidung(id) ON DELETE SET NULL,
    ketquaxetnghiem text,
    vitriluutru varchar(255),
    ghichu varchar(255),
    trangthai varchar(20) NOT NULL DEFAULT 'choxetnghiem' CHECK (trangthai IN ('choxetnghiem', 'sansang', 'dasudung', 'huybo')),
    yeucaucanmauid integer REFERENCES yeucaucanmau(id) ON DELETE SET NULL,
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT ck_blood_unit_expiry CHECK (ngayhethan IS NULL OR ngaylaymau IS NULL OR ngayhethan > ngaylaymau)
);

CREATE TABLE nhommautuongthich (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhommauhienid integer NOT NULL REFERENCES nhommau(id) ON DELETE CASCADE,
    nhommaunhanid integer NOT NULL REFERENCES nhommau(id) ON DELETE CASCADE,
    trangthai integer NOT NULL DEFAULT 1 CHECK (trangthai IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_compatible_blood_pair UNIQUE (nhommauhienid, nhommaunhanid),
    CONSTRAINT ck_compatible_blood_distinct CHECK (nhommauhienid <> nhommaunhanid)
);

CREATE TABLE danhmucbaiviet (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tieude text NOT NULL,
    noidung text NOT NULL,
    trangthai integer NOT NULL DEFAULT 1 CHECK (trangthai IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE baiviet (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tieude text NOT NULL,
    anh varchar(255) NOT NULL,
    danhmucid integer NOT NULL REFERENCES danhmucbaiviet(id) ON DELETE RESTRICT,
    noidung text NOT NULL,
    luotxem integer NOT NULL DEFAULT 0 CHECK (luotxem >= 0),
    nguoitao integer NOT NULL,
    trangthai integer NOT NULL DEFAULT 1 CHECK (trangthai IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE thongbao (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tieude text NOT NULL,
    anh varchar(255) NOT NULL,
    nguoitaoid integer NOT NULL REFERENCES nguoidung(id) ON DELETE RESTRICT,
    noidung text NOT NULL,
    ngaybatdau date NOT NULL,
    ngayketthuc date NOT NULL,
    trangthai integer NOT NULL DEFAULT 1 CHECK (trangthai IN (0, 1)),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_notification_dates CHECK (ngayketthuc >= ngaybatdau)
);

CREATE TABLE yeucaulienhehotro (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoidungid integer NOT NULL REFERENCES nguoidung(id) ON DELETE RESTRICT,
    hoten varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    sodienthoai varchar(20) NOT NULL,
    tieude varchar(255) NOT NULL,
    noidung text NOT NULL,
    trangthai varchar(20) NOT NULL DEFAULT 'moi' CHECK (trangthai IN ('moi', 'dangxuly', 'hoanthanh', 'dahuy')),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lichsulienhehotro (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotroid integer REFERENCES yeucaulienhehotro(id) ON DELETE CASCADE,
    nguoihotroid integer NOT NULL REFERENCES nguoidung(id) ON DELETE RESTRICT,
    ghichu text NOT NULL,
    trangthai varchar(20) NOT NULL DEFAULT 'moi' CHECK (trangthai IN ('moi', 'dangxuly', 'hoanthanh', 'dahuy')),
    ngaytao timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngaycapnhat timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_blood ON nguoidung (nhommauid);
CREATE INDEX idx_user_role_status ON nguoidung (vaitro, trangthai);
CREATE INDEX idx_employee_user ON thongtinnhanvien (nguoidungid);
CREATE INDEX idx_activity_status_dates ON hoatdonghienmau (trangthaihoatdong, ngaybatdau, ngayketthuc);
CREATE INDEX idx_activity_creator ON hoatdonghienmau (nguoitaoid);
CREATE INDEX idx_donation_request_status_date ON yeucauhienmau (trangthai, ngayhienmaudukien);
CREATE INDEX idx_donation_request_donor ON yeucauhienmau (nguoihienid);
CREATE INDEX idx_donation_request_activity ON yeucauhienmau (hoatdonghienmauid);
CREATE INDEX idx_receive_request_status_date ON yeucaucanmau (trangthai, ngaynhanmaudukien);
CREATE INDEX idx_receive_request_recipient ON yeucaucanmau (nguoinhanid);
CREATE INDEX idx_receive_request_blood ON yeucaucanmau (nhommauid);
CREATE INDEX idx_blood_unit_status_expiry ON khodonvimau (trangthai, ngayhethan);
CREATE INDEX idx_blood_unit_blood ON khodonvimau (nhommauid);
CREATE INDEX idx_blood_unit_receive_request ON khodonvimau (yeucaucanmauid);
CREATE INDEX idx_compatible_blood_target ON nhommautuongthich (nhommaunhanid);
CREATE INDEX idx_blog_category_status ON baiviet (danhmucid, trangthai);
CREATE INDEX idx_notification_active_dates ON thongbao (trangthai, ngaybatdau, ngayketthuc);
CREATE INDEX idx_support_ticket_status_date ON yeucaulienhehotro (trangthai, ngaytao);
CREATE INDEX idx_support_ticket_user ON yeucaulienhehotro (nguoidungid);
CREATE INDEX idx_support_history_ticket ON lichsulienhehotro (hotroid);
